application: backupbackend
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /favicon.ico
  static_files: templates/favicon.ico
  upload: templates/favicon.ico

- url: /ajax.js
  static_files: templates/ajax.js
  upload: templates/ajax.js

- url: /login.css
  static_files: templates/login.css
  upload: templates/login.css

- url: /style.css
  static_files: templates/style.css
  upload: templates/style.css


- url: /static
  static_dir: static

- url: /img
  static_dir: img


- url: /.*
  script: blog.app
  secure: always

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"
